version: 'not working'
services:
  jupyter:
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
    volumes:
      - "/mnt/e/tmp:/home/jovyan/work"
    environment:
      - JUPYTER_ENABLE_LAB=yes

  rstudio:
    image: rocker/rstudio
    ports:
      - "8787:8787"
    environment:
      - DISABLE_AUTH=true
    volumes:
      - "/mnt/e/tmp:/home/rstudio"
